[theme]
dark = 'rasmus_transparent'
light = 'flatwhite'
# fallback = "flatwhite"

[editor]
mouse = false
line-number = 'relative'
scrolloff = 5
idle-timeout = 0
auto-pairs = true
color-modes = true
cursorline = true
true-color = true
# rulers = [80, 120]
bufferline = 'multiple'
jump-label-alphabet = 'hjklabcdefgimnopqrstuvwxyz'

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
git-ignore = true
hidden = false

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']
C-h = 'jump_view_left'
C-l = 'jump_view_right'
D = 'kill_to_line_end'
A-D = 'kill_to_line_start'
# y = { y = ['extend_to_line_bounds', 'yank'] }

C-g = [
  ':new',
  ':insert-output lazygit',
  ':buffer-close!',
  ':redraw',
  ':reload-all',
]

[keys.normal.space]
l = ':toggle lsp.display-inlay-hints'
t = ':theme rasmus_transparent'

[keys.normal.space.space]
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"

[keys.insert]
esc = ['collapse_selection', 'normal_mode']
C-c = ['collapse_selection', 'normal_mode']
C-h = ['move_char_left']
C-l = ['move_char_right']
