theme = 'fleet_dark'

[editor]
mouse = false
line-number = 'relative'
scrolloff = 5
idle-timeout = 0
auto-pairs = true
color-modes = true
cursorline = true
true-color = true
# rulers = [ 80 ]
bufferline = 'multiple'

[editor.cursor-shape]
insert = 'bar'
select = 'underline'

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.file-picker]
git-ignore = true
hidden = false

[editor.indent-guides]
# render = true

[keys.normal]
esc = ['collapse_selection', 'keep_primary_selection']

[keys.insert]
esc = [':format', 'normal_mode']
'C-c' = 'normal_mode'

[keys.select]
