theme = "catppuccin_macchiato"

[editor]
mouse = false
line-number = "relative"
scrolloff = 5
idle-timeout = 0
auto-pairs = false
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[editor.file-picker]
hidden = false
