[colors]
ansi = [
	'#5c6a72',
	'#f85552',
	'#8da101',
	'#dfa000',
	'#3a94c5',
	'#df69ba',
	'#35a77c',
	'#e8e5d5',
]
background = '#fffbef'
brights = [
	'#5c6a72',
	'#f85552',
	'#8da101',
	'#dfa000',
	'#3a94c5',
	'#df69ba',
	'#35a77c',
	'#e8e5d5',
]
cursor_bg = '#5c6a72'
cursor_border = '#5c6a72'
cursor_fg = '#fffbef'
foreground = '#5c6a72'

[colors.indexed]

[metadata]
name = 'Everforest Light (Hard)'
origin_url = 'https://github.com/frdwin/Everforest-Wezterm'
