# original colors have been mathematically darkened to work in the terminal
[colors]
ansi = [
  '#605a52',
  '#b57c09',
  '#bdcd72',
  '#eaad61',
  '#89a1d1',
  '#cf8bcf',
  '#84c8b3',
  '#4d1dd5',
]
brights = [
  '#605a52',
  '#b57c09',
  '#bdcd72',
  '#eaad61',
  '#89a1d1',
  '#cf8bcf',
  '#84c8b3',
  '#4d1dd5',
]

background = '#f7f3ee'
foreground = '#605a52'

compose_cursor = '#990000'
cursor_bg = '#605a52'
cursor_border = '#605a52'
cursor_fg = '#f7f3ee'

selection_bg = '#dcd3c6'
selection_fg = '#605a52'

scrollbar_thumb = '#ff0000'
split = '#dcd3c6'

[colors.indexed]

[colors.tab_bar]
background = '#e4ddd2'

[colors.tab_bar.active_tab]
bg_color = '#f7f3ee'
fg_color = '#605a52'

[colors.tab_bar.inactive_tab]
bg_color = '#e4ddd2'
fg_color = '#605a52'

[colors.tab_bar.inactive_tab_hover]
bg_color = '#605a52'
fg_color = '#f7f3ee'

[colors.tab_bar.new_tab]
bg_color = '#f7f3ee'
fg_color = '#605a52'

[colors.tab_bar.new_tab_hover]
bg_color = '#605a52'
fg_color = '#f7f3ee'

[metadata]
name = 'flatwhite'
