[colors]
ansi = [
  '#333332',
  '#ff968c',
  '#61957f',
  '#ffc591',
  '#8db4d4',
  '#de9bc8',
  '#7bb099',
  '#d1d1d1',
]
brights = [
  '#4c4c4b',
  '#ffafa5',
  '#7aae98',
  '#ffdeaa',
  '#a6cded',
  '#f7b4e1',
  '#94c9b2',
  '#eaeaea',
]

background = '#000000'
# background = '#0d0d0d'
# background = '#1a1a19'
foreground = '#d1d1d1'

compose_cursor = '#b6b6b5'
cursor_fg = '#333332'
cursor_bg = '#b6b6b5'
cursor_border = '#605a52'

selection_fg = '#d1d1d1'
selection_bg = '#2a2a29'

scrollbar_thumb = '#ff0000'
split = '#dcd3c6'

[colors.indexed]

# [colors.tab_bar]
# background = '#e4ddd2'

# [colors.tab_bar.active_tab]
# bg_color = '#f7f3ee'
# fg_color = '#605a52'

# [colors.tab_bar.inactive_tab]
# bg_color = '#e4ddd2'
# fg_color = '#605a52'

# [colors.tab_bar.inactive_tab_hover]
# bg_color = '#605a52'
# fg_color = '#f7f3ee'

# [colors.tab_bar.new_tab]
# bg_color = '#f7f3ee'
# fg_color = '#605a52'

# [colors.tab_bar.new_tab_hover]
# bg_color = '#605a52'
# fg_color = '#f7f3ee'

[metadata]
name = 'rasmus'
